# Generated by Django 3.1.6 on 2022-06-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('term', models.IntegerField()),
                ('term_min', models.IntegerField(blank=True, null=True)),
                ('term_max', models.IntegerField(blank=True, null=True)),
                ('rate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
