# Generated by Django 3.1.6 on 2022-06-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_getoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getoffer',
            name='deposit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='term',
            field=models.IntegerField(null=True),
        ),
    ]
