# Generated by Django 3.1.6 on 2022-06-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220612_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getoffer',
            old_name='term_max',
            new_name='payment_max',
        ),
        migrations.RenameField(
            model_name='getoffer',
            old_name='term_min',
            new_name='payment_min',
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='deposit',
            field=models.IntegerField(default=500000, null=True),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='price',
            field=models.IntegerField(default=5000000, null=True),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='term',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
