# Generated by Django 3.1.6 on 2022-06-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220612_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='getoffer',
            name='offer_id',
            field=models.ManyToManyField(to='api.Offer'),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='deposit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='term',
            field=models.IntegerField(null=True),
        ),
    ]
