# Generated by Django 3.1.6 on 2022-06-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220612_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getoffer',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='getoffer',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='getoffer',
            name='offer_id',
        ),
        migrations.RemoveField(
            model_name='getoffer',
            name='payment_max',
        ),
        migrations.RemoveField(
            model_name='getoffer',
            name='payment_min',
        ),
        migrations.RemoveField(
            model_name='getoffer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='getoffer',
            name='rate_max',
        ),
        migrations.RemoveField(
            model_name='getoffer',
            name='rate_min',
        ),
        migrations.RemoveField(
            model_name='getoffer',
            name='term',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='term',
        ),
    ]
